### ISSUE TITLE
Require separate lodash functions instead of full lib

### ISSUE THREAD

**Issue by bartekn** [stellar/js-xdr#12]
It should save around 50kB according to: https://github.com/stellar/js-stellar-sdk/issues/138#issuecomment-372790058

**Comment by nullstyle** [comment]
This already mostly done here:  https://github.com/stellar/js-xdr/pull/10

We just need to get debugging done with the babel bullshit you mentioned.

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/js-xdr/pull/14.
