### ISSUE TITLE
introduce safe reads

### ISSUE THREAD

**Issue by tomerweller** [stellar/js-xdr#32]
There isn't a way to read an XDR structure in a way that ensures that the entire read buffer is consumed. 

For example, Stellar's XDR schema has both a `Transaction` and a `TransactionEnvelope` which includes a `Transaction` as it's prefix. 

One could unmarshal a `TransactionEnvelope` as a `Transaction` (or even an `Int64`) while in practice it should have failed.

**Comment by Shaptic** [comment]
Closed by #91.
