### ISSUE TITLE
toXdr method of io-mixin can cause out of range error

### ISSUE THREAD

**Issue by pieterjan84** [stellar/js-xdr#84]
**Describe the bug**
Calling the toXdr() method on io-mixin can cause an out of range error because the Buffer used has a fixed size: 
https://github.com/stellar/js-xdr/blob/a060f75d29999a11c188471787a8845d2e1d9185/src/io-mixin.js#L6

**What version are you on?**
1.3.0

**To Reproduce**
https://gist.github.com/pieterjan84/e99aea29935308be1d935946bb33699f

**Possible solution**
The issue is marked as TODO in the code, maybe the following could be an easy solution:

1. Add _ensureBufferIsBigEnough method to Cursor:

```
function _ensureBufferIsBigEnough(nrOfBytesToWrite){
      if(this.tell() + nrOfBytesToWrite <= this.buffer().length)
        return; //big enough

      const biggerBuffer = Buffer.alloc(this.buffer().length * 2); //what should the scaling factor be?
      this.buffer().copy(biggerBuffer);
      this._setBuffer(biggerBuffer);
    }
```
2. Call method before every write action in Cursor. 

If this solution is ok I can supply a pull request.

**Comment by Shaptic** [comment]
Closed by #91.
